import { StyleSheet } from "react-native";

export const colors = {
  background: "#07090d",
  carbon: "#0e1117",
  surface: "#111720",
  elevated: "#181e27",
  graphite: "#151922",
  steel: "#202733",
  text: "#f4f1e8",
  muted: "#aeb7c5",
  gold: "#c8a96b",
  goldDark: "#9f7d3f",
  goldStrong: "#e8d2a4",
  cyan: "#39d0ff",
  cyanDeep: "#128db5",
  ice: "#9fe8ff",
  border: "#3f4d5e",
  success: "#2ad67a",
  warning: "#ffb84d",
  danger: "#ff5d5d",
  intel: "#8b6cff",
};
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 18,
    paddingTop: 20,
    gap: 14,
  },
  title: {
    color: colors.text,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.8,
    lineHeight: 35,
    textAlign: "auto",
    writingDirection: "auto",
  },
  subtitle: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 24,
    textAlign: "auto",
    writingDirection: "auto",
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 2,
    borderBottomLeftRadius: 16,
    padding: 18,
    gap: 10,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.42,
    shadowRadius: 24,
    elevation: 10,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0.35,
    textAlign: "auto",
    writingDirection: "auto",
  },
  value: {
    color: colors.gold,
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.35,
    textAlign: "auto",
    writingDirection: "auto",
  },
  text: { color: colors.text, textAlign: "auto", writingDirection: "auto" },
  muted: { color: colors.muted, textAlign: "auto", writingDirection: "auto" },
  input: {
    minHeight: 52,
    color: colors.text,
    backgroundColor: colors.carbon,
    borderWidth: 1,
    borderColor: colors.border,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 2,
    borderBottomLeftRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  button: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.gold,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 2,
    borderBottomLeftRadius: 10,
    backgroundColor: colors.elevated,
    paddingHorizontal: 18,
    paddingVertical: 12,
    shadowColor: colors.gold,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  buttonText: {
    color: colors.goldStrong,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  secondaryButton: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 2,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 2,
    borderBottomLeftRadius: 10,
    borderWidth: 1,
    borderColor: colors.cyanDeep,
    backgroundColor: colors.carbon,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: colors.ice,
    fontWeight: "800",
    letterSpacing: 0.55,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  progressTrack: {
    height: 7,
    overflow: "hidden",
    borderRadius: 1,
    backgroundColor: colors.steel,
  },
  progressValue: { height: 7, backgroundColor: colors.gold },
  sectionTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0.2,
    textAlign: "auto",
    writingDirection: "auto",
  },
  list: { gap: 12, paddingBottom: 118 },
});
