// Generated by pnpm i18n:bootstrap. Do not edit by hand.
import type { RequiredLocale } from "@shadowgrid/game-config";
import catalog_en_common from "../locales/en/common.json";
import catalog_en_auth from "../locales/en/auth.json";
import catalog_en_economy from "../locales/en/economy.json";
import catalog_en_exchange from "../locales/en/exchange.json";
import catalog_en_cartels from "../locales/en/cartels.json";
import catalog_en_intelligence from "../locales/en/intelligence.json";
import catalog_en_seasons from "../locales/en/seasons.json";
import catalog_en_narrative from "../locales/en/narrative.json";
import catalog_en_engagement from "../locales/en/engagement.json";
import catalog_en_legal from "../locales/en/legal.json";
import catalog_en_store from "../locales/en/store.json";
import catalog_en_support from "../locales/en/support.json";

export type RuntimeCatalog = Record<string, string>;

const mergeCatalogs = (...catalogs: RuntimeCatalog[]): RuntimeCatalog =>
  Object.assign({}, ...catalogs);

export const runtimeApprovedLocales = ["en"] as const satisfies readonly RequiredLocale[];
export const localeMetadata = {
  "en": {
    "name": "English",
    "script": "Latn",
    "direction": "ltr"
  },
  "zh-Hans": {
    "name": "Mandarin Chinese",
    "script": "Hans",
    "direction": "ltr"
  },
  "es": {
    "name": "Español",
    "script": "Latn",
    "direction": "ltr"
  },
  "hi": {
    "name": "हिन्दी",
    "script": "Deva",
    "direction": "ltr"
  },
  "fr": {
    "name": "Français",
    "script": "Latn",
    "direction": "ltr"
  },
  "ar": {
    "name": "العربية الفصحى الحديثة",
    "script": "Arab",
    "direction": "rtl"
  },
  "bn": {
    "name": "বাংলা",
    "script": "Beng",
    "direction": "ltr"
  },
  "pt-BR": {
    "name": "Português do Brasil",
    "script": "Latn",
    "direction": "ltr"
  },
  "id": {
    "name": "Bahasa Indonesia",
    "script": "Latn",
    "direction": "ltr"
  },
  "ur": {
    "name": "اردو",
    "script": "Aran",
    "direction": "rtl"
  },
  "ru": {
    "name": "Русский",
    "script": "Cyrl",
    "direction": "ltr"
  },
  "de": {
    "name": "Deutsch",
    "script": "Latn",
    "direction": "ltr"
  },
  "ja": {
    "name": "日本語",
    "script": "Jpan",
    "direction": "ltr"
  },
  "pcm": {
    "name": "Naijá",
    "script": "Latn",
    "direction": "ltr"
  },
  "arz": {
    "name": "مصرى",
    "script": "Arab",
    "direction": "rtl"
  },
  "mr": {
    "name": "मराठी",
    "script": "Deva",
    "direction": "ltr"
  },
  "vi": {
    "name": "Tiếng Việt",
    "script": "Latn",
    "direction": "ltr"
  },
  "te": {
    "name": "తెలుగు",
    "script": "Telu",
    "direction": "ltr"
  },
  "sw": {
    "name": "Kiswahili",
    "script": "Latn",
    "direction": "ltr"
  },
  "ha": {
    "name": "Hausa",
    "script": "Latn",
    "direction": "ltr"
  },
  "tr": {
    "name": "Türkçe",
    "script": "Latn",
    "direction": "ltr"
  },
  "pnb": {
    "name": "پنجابی",
    "script": "Aran",
    "direction": "rtl"
  },
  "fil-PH": {
    "name": "Filipino",
    "script": "Latn",
    "direction": "ltr"
  },
  "ta": {
    "name": "தமிழ்",
    "script": "Taml",
    "direction": "ltr"
  },
  "yue-Hant": {
    "name": "粵語",
    "script": "Hant",
    "direction": "ltr"
  },
  "wuu-Hans": {
    "name": "吴语",
    "script": "Hans",
    "direction": "ltr"
  },
  "fa-IR": {
    "name": "فارسی",
    "script": "Arab",
    "direction": "rtl"
  },
  "ko": {
    "name": "한국어",
    "script": "Kore",
    "direction": "ltr"
  },
  "am": {
    "name": "አማርኛ",
    "script": "Ethi",
    "direction": "ltr"
  },
  "th": {
    "name": "ไทย",
    "script": "Thai",
    "direction": "ltr"
  },
  "jv": {
    "name": "Basa Jawa",
    "script": "Latn",
    "direction": "ltr"
  },
  "it": {
    "name": "Italiano",
    "script": "Latn",
    "direction": "ltr"
  },
  "gu": {
    "name": "ગુજરાતી",
    "script": "Gujr",
    "direction": "ltr"
  },
  "kn": {
    "name": "ಕನ್ನಡ",
    "script": "Knda",
    "direction": "ltr"
  },
  "apc": {
    "name": "العربية الشامية",
    "script": "Arab",
    "direction": "rtl"
  },
  "apd": {
    "name": "العربية السودانية",
    "script": "Arab",
    "direction": "rtl"
  }
} as const satisfies Record<RequiredLocale, { name: string; script: string; direction: "ltr" | "rtl" }>;
export const runtimeApprovedCatalogs: Partial<Record<RequiredLocale, RuntimeCatalog>> = {
  "en": mergeCatalogs(catalog_en_common, catalog_en_auth, catalog_en_economy, catalog_en_exchange, catalog_en_cartels, catalog_en_intelligence, catalog_en_seasons, catalog_en_narrative, catalog_en_engagement, catalog_en_legal, catalog_en_store, catalog_en_support),
};
